Merge global refactoring to master
cds-astro/ipyaladin pull request #82
Opened 2024-04-23 07:16 UTC by Xen0Xys

2024-04-29 08:03 UTC, ManonMarchand commented
Maybe we could run the tests for the oldest and newest python versions that are supported ? (3.8 and 3.12)

2024-04-29 09:26 UTC, ManonMarchand commented on pyproject.toml
> +requires-python = ">=3.10"
3.8

2024-04-29 09:26 UTC, ManonMarchand commented on pyproject.toml
> +dev = ["ipyaladin[test]", "watchfiles", "jupyterlab", "ruff"]
we can merge test and dev together

2024-04-29 09:26 UTC, ManonMarchand commented on src/ipyaladin/__init__.py
> +        if _dWarning:
Should appear in the changelog

2024-04-29 15:30 UTC, ManonMarchand commented
Fixes #77

2024-05-02 07:33 UTC, bmatthieu3 requested changes
Just little comments on the JS part. Otherwise it is good to merge from my point of view.

2024-05-02 07:33 UTC, bmatthieu3 commented on js/imports.js
I would have call it maybe aladin_lite.js or something suggesting that it refers to aladin lite.

2024-05-02 07:33 UTC, bmatthieu3 commented on js/models/message_handler.js
> +    if (options["lineWidth"] === undefined) options["lineWidth"] = 3;
I do not think it is needed anymore. In aladin lite there is a default linewidth given if you do not explicitely give one. The default is indeed 3

2024-05-02 07:33 UTC, bmatthieu3 commented on js/models/message_handler.js
> +    if (options["lineWidth"] === undefined) options["lineWidth"] = 3;
same here

2024-05-03 12:49 UTC, Xen0Xys commented
Do not merge until the recursion bug isn't fixed !

2024-05-06 15:43 UTC, ManonMarchand commented on .github/workflows/python-tests.yml
> +        uses: actions/setup-python@v2
why the downgrade?

2024-05-06 15:43 UTC, ManonMarchand commented on src/ipyaladin/aladin.py
> +
typo: a string **or** an

2024-05-06 15:43 UTC, ManonMarchand commented on src/ipyaladin/aladin.py
> +        # http://www.astropy.org/
I think we can remove the comment as astropy is in our mandatory dependencies now

2024-05-06 15:43 UTC, ManonMarchand commented on src/ipyaladin/aladin.py
> +    # thus only the last message will be displayed at the screen
Don't know what the comment is referring to.

2024-05-07 07:15 UTC, ManonMarchand approved these changes

2024-05-07 07:36 UTC, merged